font_family                 JetBrains Mono
font_size                   14.0
disable_ligatures           never
text_composition_strategy   1.7 30

url_style                   dotted

tab_bar_style               custom
tab_separator               " ┇ "
tab_activity_symbol         •
tab_bar_margin_height       0.0 1.0
tab_bar_margin_width        0.0

foreground                  #000000
background                  #ffffff
wayland_titlebar_color      #ffffff
tab_bar_margin_color        #ebecf0
active_border_color         #ebecf0
inactive_border_color       #fafafa
