" I have moved over to neovim. My vim config rot so I got some Gemini to
" generate it using my neovim config. Some stuff in this file may therefore be
" extremely stupid, and I would never know since I rarely need vanilla vim.
" ==============================================================================

set runtimepath^=$XDG_CONFIG_HOME/vim
set runtimepath+=$XDG_DATA_HOME/vim
set runtimepath+=$XDG_CONFIG_HOME/vim/after

set packpath^=$XDG_DATA_HOME/vim,$XDG_CONFIG_HOME/vim
set packpath+=$XDG_CONFIG_HOME/vim/after,$XDG_DATA_HOME/vim/after

let g:netrw_home = $XDG_DATA_HOME."/vim"
call mkdir($XDG_DATA_HOME."/vim/spell", 'p')

set backupdir=$XDG_STATE_HOME/vim/backup | call mkdir(&backupdir, 'p')
set directory=$XDG_STATE_HOME/vim/swap   | call mkdir(&directory, 'p')
set undodir=$XDG_STATE_HOME/vim/undo     | call mkdir(&undodir,   'p')
set viewdir=$XDG_STATE_HOME/vim/view     | call mkdir(&viewdir,   'p')

if !has('nvim') | set viminfofile=$XDG_STATE_HOME/vim/viminfo | endif

" ==============================================================================

set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set mouse=
set relativenumber
set smarttab
set formatoptions+=cro shortmess-=S termguicolors updatetime=100 tw=0
" (an asterisk in the beginning of each line of a multi-line comment in c)
" note the +, I want the opposite behavior of:
" https://www.reddit.com/r/vim/comments/9kz5rk/format_of_c_comments/

" let $PAGER=''
runtime! ftplugin/man.vim

nnoremap <F2> :set relativenumber!<CR>
nnoremap <F3> :noh<CR>

nnoremap <silent> <C-j> :wincmd j<CR>
nnoremap <silent> <C-k> :wincmd k<CR>
nnoremap <silent> <C-h> :wincmd h<CR>
nnoremap <silent> <C-l> :wincmd l<CR>

nnoremap <M-u> <C-u>
vnoremap <M-u> <C-u>
nnoremap <M-d> <C-d>
vnoremap <M-d> <C-d>
nnoremap <M-f> <C-f>
vnoremap <M-f> <C-f>
nnoremap <M-b> <C-b>
vnoremap <M-b> <C-b>
nnoremap <M-o> <C-o>
nnoremap <M-i> <C-i>

map Y y$

nnoremap <expr> j v:count == 0 ? 'gj' : "m'" . v:count . 'j'
nnoremap <expr> k v:count == 0 ? 'gk' : "m'" . v:count . 'k'
vnoremap <expr> j v:count == 0 ? 'gj' : "m'" . v:count . 'j'
vnoremap <expr> k v:count == 0 ? 'gk' : "m'" . v:count . 'k'

nnoremap $ g$
nnoremap 0 g0
nnoremap gj j
nnoremap gk k
nnoremap g$ $
nnoremap g0 0
vnoremap $ g$
vnoremap 0 g0
vnoremap gj j
vnoremap gk k
vnoremap g$ $
vnoremap g0 0

" Remove any mapping from the space key in normal mode (to use as leader)
nnoremap <SPACE> <Nop>
let mapleader = " "

vnoremap <M-c> "+y

tmap <C-h> <C-W><C-h>
tmap <C-l> <C-W><C-l>
tmap <C-j> <C-W><C-j>
tmap <C-k> <C-W><C-k>

augroup FT_Configs
    autocmd!
    autocmd FileType lex,c,asm,make setlocal tabstop=8 shiftwidth=8 textwidth=80 noexpandtab nolinebreak nospell
    autocmd FileType sh setlocal tabstop=4 shiftwidth=4 textwidth=80 noexpandtab nolinebreak nospell
    autocmd FileType cpp,cuda setlocal tabstop=4 shiftwidth=4 textwidth=99 noexpandtab nolinebreak nospell
    autocmd FileType html,css,xml,json,javascript setlocal textwidth=99 noexpandtab nolinebreak
    autocmd FileType python,lua setlocal textwidth=99 nolinebreak nospell
    autocmd FileType tex setlocal tabstop=2 softtabstop=2 shiftwidth=2 textwidth=80 expandtab spell
    autocmd FileType markdown setlocal textwidth=80 linebreak spell
    autocmd FileType scheme,racket,haskell setlocal tabstop=2 softtabstop=2 shiftwidth=2 textwidth=80
    autocmd FileType rst setlocal tabstop=8 shiftwidth=8 textwidth=80 noexpandtab linebreak spell
    autocmd FileType txt,typst setlocal spell
    autocmd BufRead,BufNewFile *.ixx set filetype=cpp
augroup END

function! s:SetKittyVar(val)
    let l:cmd = "\x1b]1337;SetUserVar=in_editor=" . a:val . "\x07"
    if has('gui_running')
        return
    endif
    let l:out = &t_te . l:cmd
    call writefile([l:cmd], "/dev/stdout", "b")
endfunction

augroup KittyVar
    autocmd!
    " MQo is base64 for '1'
    autocmd VimEnter,VimResume * call s:SetKittyVar("MQo")
    autocmd VimLeave,VimSuspend * call s:SetKittyVar("")
augroup END

" (no plugins required) debugging inside vim:
let g:termdebug_wide = 1
