# xremap /home/aditya/.config/xremap/config.yml

modmap:
  - name: Global
    remap:
      rightalt:
        held: fn
        alone: fn
      capslock: esc

virtual_modifiers:
  - fn

keymap:
  - name: right alt layer
    remap:
      kp5: down
      fn-1: f1
      fn-2: f2
      fn-3: f3
      fn-4: f4
      fn-5: f5
      fn-6: f6
      fn-7: f7
      fn-8: f8
      fn-9: f9
      fn-0: f10
      fn-minus: f11
      fn-equal: f12
      fn-h: left
      fn-j: down
      fn-k: up
      fn-l: right
      fn-semicolon: home
      fn-apostrophe: end
      fn-leftbrace: pageup
      fn-slash: pagedown
      fn-tab: alt-tab

  - name: disable stupid linux touchpads
    remap:
      nextsong:
        launch: ["/home/aditya/.local/bin/toggle-touchpad-clicks"]

  - name: comfy keymap
    exact_match: true
    application:
      not: [kitty,
            zen,
            zen-twilight,
            zen-beta,
            zen-alpha,
            jetbrains-idea,
            jetbrains-clion,
            jetbrains-pycharm,
            jetbrains-rustrover,
            jetbrains-dataspell,
            dev.zed.Zed,
            dev.zed.Zed-Dev,
            dev.zed.Zed-Preview,
            com.raggesilver.BlackBox,
            virt-manager,
            qemu-system-x86_64,
            ghostty,
            mpv,
            # sioyek, # sioyek has ctrl-v hardcoded for paste in search bar
            # Cursor, # Cursor does not allow remapping non-editor shortcuts
            ]
    remap:
      alt_L-a: C-a
      alt_L-b: C-b
      alt_L-c: C-c
      alt_L-d: C-d
      alt_L-e: C-e
      alt_L-f: C-f
      alt_L-g: C-g
      alt_L-h: C-h
      alt_L-i: C-i
      alt_L-j: C-j
      alt_L-k: C-k
      alt_L-l: C-l
      alt_L-m: C-m
      alt_L-n: C-n
      alt_L-o: C-o
      alt_L-p: C-p
      alt_L-q: C-q
      alt_L-r: C-r
      alt_L-s: C-s
      alt_L-t: C-t
      alt_L-u: C-u
      alt_L-v: C-v
      alt_L-w: C-w
      alt_L-x: C-x
      alt_L-y: C-y
      alt_L-z: C-z
      alt_L-backspace: C-backspace

      alt_l-leftbrace: C-leftbrace
      alt_l-rightbrace: C-rightbrace

      alt_l-minus: c-minus
      alt_l-equal: c-equal
      alt_l-shift-equal: C-shift-equal

      alt_l-shift-a: C-shift-a
      alt_l-shift-b: C-shift-b
      alt_l-shift-c: C-shift-c
      alt_l-shift-d: C-shift-d
      alt_l-shift-e: C-shift-e
      alt_l-shift-f: C-shift-f
      alt_l-shift-g: C-shift-g
      alt_l-shift-h: C-shift-h
      alt_l-shift-i: C-shift-i
      alt_l-shift-j: C-shift-j
      alt_l-shift-k: C-shift-k
      alt_l-shift-l: C-shift-l
      alt_l-shift-m: C-shift-m
      alt_l-shift-n: C-shift-n
      alt_l-shift-o: C-shift-o
      alt_l-shift-p: C-shift-p
      alt_l-shift-q: C-shift-q
      alt_l-shift-r: C-shift-r
      alt_l-shift-s: C-shift-s
      alt_l-shift-t: C-shift-t
      alt_l-shift-u: C-shift-u
      alt_l-shift-v: C-shift-v
      alt_l-shift-w: C-shift-w
      alt_l-shift-x: C-shift-x
      alt_l-shift-y: C-shift-y
      alt_l-shift-z: C-shift-z

  - name: zen browser
    exact_match: true
    application:
      only: [zen,
             zen-twilight,
             zen-beta,
             zen-alpha]
    remap:
      ctrl_L-s: C-alt-s
      ctrl_L-c: C-alt-c
      ctrl_L-h: C-alt-h
      ctrl_L-v: C-alt-v
      ctrl_L-g: C-alt-g
      ctrl_L-u: C-alt-u
      alt_L-tab: C-tab
      alt_L-a: C-a
      alt_L-b: C-b
      alt_L-c: C-c
      alt_L-d: C-d
      alt_L-e: C-e
      alt_L-f: C-f
      alt_L-g: C-g
      alt_L-h: C-h
      alt_L-i: C-i
      alt_L-j: C-j
      alt_L-k: C-k
      alt_L-l: C-l
      alt_L-m: C-m
      alt_L-n: C-n
      alt_L-o: C-o
      alt_L-p: C-p
      alt_L-q: C-q
      alt_L-r: C-r
      alt_L-s: C-s
      alt_L-t: C-t
      alt_L-u: C-u
      alt_L-v: C-v
      alt_L-w: C-w
      alt_L-x: C-x
      alt_L-y: C-y
      alt_L-z: C-z
      alt_L-backspace: C-backspace

      alt_l-leftbrace: C-pageup
      alt_l-rightbrace: C-pagedown

      alt_l-minus: c-minus
      alt_l-equal: c-equal
      alt_l-shift-equal: C-shift-equal

      alt_l-shift-a: C-shift-a
      alt_l-shift-b: C-shift-b
      alt_l-shift-c: C-shift-c
      alt_l-shift-d: C-shift-d
      alt_l-shift-e: C-shift-e
      alt_l-shift-f: C-shift-f
      alt_l-shift-g: C-shift-g
      alt_l-shift-h: C-shift-h
      alt_l-shift-i: C-shift-i
      alt_l-shift-j: C-shift-j
      alt_l-shift-k: C-shift-k
      alt_l-shift-l: C-shift-l
      alt_l-shift-m: C-shift-m
      alt_l-shift-n: C-shift-n
      alt_l-shift-o: C-shift-o
      alt_l-shift-p: C-shift-p
      alt_l-shift-q: C-shift-q
      alt_l-shift-r: C-shift-r
      alt_l-shift-s: C-shift-s
      alt_l-shift-t: C-shift-t
      alt_l-shift-u: C-shift-u
      alt_l-shift-v: C-shift-v
      alt_l-shift-w: C-shift-w
      alt_l-shift-x: C-shift-x
      alt_l-shift-y: C-shift-y
      alt_l-shift-z: C-shift-z
