# https://wiki.hypr.land/Configuring/Window-Rules/
# https://wiki.hypr.land/Configuring/Workspace-Rules/

# For my tiling plugin
windowrule = float, class:.*

# For clients that do not remember window size and launch at a stupid size
windowrule = size 1087  722, class:^(org.freedesktop.impl.portal.desktop.kde)$
windowrule = size 1500 1280, class:^(zen)$
windowrule = size 1280  800, class:^(neovide)$

# Ignore maximize requests from apps.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0
