# https://wiki.hypr.land/Configuring/Window-Rules/
# https://wiki.hypr.land/Configuring/Workspace-Rules/

# For my tiling plugin
windowrule = float on, match:class .*

# For clients that do not remember window size and launch at a stupid size
windowrule = size 1087  722, match:class ^(org.freedesktop.impl.portal.desktop.kde)$
windowrule = size 1500 1280, match:class ^(zen)$
windowrule = size 1280  800, match:class ^(neovide)$

# Ignore maximize requests from apps.
windowrule = suppress_event maximize, match:class .*

# Fix some dragging issues with XWayland
windowrule = no_focus on, match:class ^$, match:title ^$, match:xwayland 1, match:float 1, match:fullscreen 0, match:pin 0
