local utils = require("config.utils")

-- credits: Kovid Goyal
vim.api.nvim_create_autocmd({ "VimEnter", "VimResume", "UIEnter" }, {
    group = vim.api.nvim_create_augroup("KittySetVarVimEnter", { clear = true }),
    callback = function()
        if vim.api.nvim_ui_send then
            vim.api.nvim_ui_send("\x1b]1337;SetUserVar=in_editor=MQ==\007")
        else
            io.stdout:write("\x1b]1337;SetUserVar=in_editor=MQ==\007")
        end
    end,
})

-- credits: Kovid Goyal
vim.api.nvim_create_autocmd({ "VimLeave", "VimSuspend" }, {
    group = vim.api.nvim_create_augroup("KittyUnsetVarVimLeave", { clear = true }),
    callback = function()
        if vim.api.nvim_ui_send then
            vim.api.nvim_ui_send("\x1b]1337;SetUserVar=in_editor\007")
        else
            io.stdout:write("\x1b]1337;SetUserVar=in_editor\007")
        end
    end,
})

-- credits: https://github.com/jdhao/nvim-config
vim.api.nvim_create_autocmd("BufWritePre", {
    pattern = "*",
    group = vim.api.nvim_create_augroup("auto_create_dir", {clear = true}),
    callback = function(ctx)
        local dir = vim.fn.fnamemodify(ctx.file, ":p:h")
        utils.may_create_dir(dir)
    end,
})

-- Generated by Claude:claude-sonnet-4.6
vim.api.nvim_create_autocmd("VimResized", {
    pattern = "*",
    desc = "Re-format man buffer when the window is resized.",
    callback = function()
        if vim.bo.filetype == "man" then
            vim.schedule(function() vim.cmd("e") end)
        end
    end,
})

vim.api.nvim_create_autocmd({"BufRead", "BufNewFile"}, {
    pattern = "*.ixx",
    callback = function()
        vim.bo.filetype = "cpp"
    end,
})

vim.api.nvim_create_autocmd("FileType", {
    pattern = {"lex", "asm", "make"},
    callback = function()
        vim.opt.tabstop = 8
        vim.opt.shiftwidth = 8
        vim.opt.textwidth = 80
        vim.opt.expandtab = false
        vim.opt.linebreak = false
    end
})

vim.api.nvim_create_autocmd("FileType", {
    pattern = "yacc",
    callback = function()
        vim.opt.commentstring = "// %s"
    end
})

vim.api.nvim_create_autocmd("FileType", {
    pattern = {"c", "cpp", "cuda", "html", "css", "xml", "json", "javascript"},
    callback = function()
        vim.opt.textwidth = 99
        vim.opt.expandtab = false
        vim.opt.linebreak = false
    end
})

vim.api.nvim_create_autocmd("FileType", {
    pattern = {"python", "lua"},
    callback = function()
        vim.opt.textwidth = 99
        vim.opt.linebreak = false
    end
})

vim.api.nvim_create_autocmd("FileType", {
    pattern = {"scheme", "racket", "haskell"},
    callback = function()
        vim.opt.tabstop = 2
        vim.opt.softtabstop = 2
        vim.opt.shiftwidth = 2
        vim.opt.textwidth = 80
    end
})

vim.api.nvim_create_autocmd("FileType", {
    pattern = {"tex", "typst"},
    callback = function()
        vim.opt.tabstop = 2
        vim.opt.softtabstop = 2
        vim.opt.shiftwidth = 2
        vim.opt.textwidth = 80
        vim.opt.spell = true
    end
})

vim.api.nvim_create_autocmd("FileType", {
    pattern = {"markdown", "txt"},
    callback = function()
        vim.opt.textwidth = 80
        vim.opt.spell = true
    end
})

vim.api.nvim_create_autocmd("FileType", {
    pattern = "rst",
    callback = function()
        vim.opt.tabstop = 8
        vim.opt.shiftwidth = 8
        vim.opt.textwidth = 80
        vim.opt.expandtab = false
        vim.opt.spell = true
    end
})
