# Adapted from https://github.com/alexpasmantier/television/blob/main/themes/solarized-light.toml
# general
background = '#ffffff'
border_fg = '#93a1a1'
text_fg = '#b58900'
dimmed_text_fg = '#d8d8d8'
# input
input_text_fg = '#d8d8d8'
result_count_fg = '#d8d8d8'
# results
result_name_fg = '#268bd2'
result_line_number_fg = '#b58900'
result_value_fg = '#93a1a1'
selection_fg = '#859900'
selection_bg = '#e6e6e7'
match_fg = '#cb4b16'
# preview
preview_title_fg = '#859900'
# modes
channel_mode_fg = '#fdf6e3'
channel_mode_bg = '#2aa198'
remote_control_mode_bg = '#fdf6e3'
remote_control_mode_fg = '#859900'
# send_to_channel_mode_fg = '#dc322f'
